name: Build LaTeX PDF

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX and compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: storycards.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: storycards.pdf
